#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
EXPOSE 80
EXPOSE 443
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Presentation/PhungDKH.Api/PhungDKH.Api.csproj", "Presentation/PhungDKH.Api/"]
COPY ["Presentation/PhungDKH.Application/PhungDKH.Application.csproj", "Presentation/PhungDKH.Application/"]
COPY ["Core/PhungDKH.Domain/PhungDKH.Domain.csproj", "Core/PhungDKH.Domain/"]
COPY ["Core/PhungDKH.Shared/PhungDKH.Shared.csproj", "Core/PhungDKH.Shared/"]
RUN dotnet restore "Presentation/PhungDKH.Api/PhungDKH.Api.csproj"
COPY . .
WORKDIR "/src/Presentation/PhungDKH.Api"
RUN dotnet build "PhungDKH.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PhungDKH.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN dotnet dev-certs https
ENTRYPOINT ["dotnet", "PhungDKH.Api.dll"]