#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
EXPOSE 80
EXPOSE 443
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Presentation/SampleProject.Api/SampleProject.Api.csproj", "Presentation/SampleProject.Api/"]
COPY ["Presentation/SampleProject.Application/SampleProject.Application.csproj", "Presentation/SampleProject.Application/"]
COPY ["Core/SampleProject.Domain/SampleProject.Domain.csproj", "Core/SampleProject.Domain/"]
COPY ["Core/SampleProject.Shared/SampleProject.Shared.csproj", "Core/SampleProject.Shared/"]
RUN dotnet restore "Presentation/SampleProject.Api/SampleProject.Api.csproj"
COPY . .
WORKDIR "/src/Presentation/SampleProject.Api"
RUN dotnet build "SampleProject.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "SampleProject.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
RUN dotnet dev-certs https
ENTRYPOINT ["dotnet", "SampleProject.Api.dll"]